// ignore_for_file: non_constant_identifier_names

import 'package:flutter/widgets.dart';

class Constants {
  static Color mov = const Color(0xff8A88F5);
  static Color lightG = const Color(0xff7DDBE9);
  static Color darkG = const Color(0xff5EC0C0);
  static Color bmba = const Color(0xffEE9CCF);
  static var days = {
    "Saturday": 0.0,
    "Sunday": 1.0,
    "Monday": 2.0,
    "Tuesday": 3.0,
    "Wednesday": 4.0,
    "Thursday": 5.0,
    "Friday": 6.0,
  };
  // List<String>
  static List<List<dynamic>> all_data = [
    [
      5681,
      18.0,
      [20.0, 6.0, 0.0]
    ],
    [
      2668,
      19.0,
      [20.0, 6.0, 0.0]
    ],
    [
      3056,
      18.0,
      [20.0, 6.0, 0.0]
    ],
    [
      3037,
      18.0,
      [20.0, 6.0, 0.0]
    ],
    [
      4102,
      18.0,
      [20.0, 6.0, 0.0]
    ],
    [
      6290,
      18.0,
      [20.0, 6.0, 0.0]
    ],
    [
      3308,
      18.0,
      [20.0, 6.0, 0.0]
    ]
  ];

  static List<double> total_quntity_fordays = [
    17874,
    9780,
    10296,
    9875,
    13776,
    20477,
    10963
  ];
  static List<String> foodnames = [
    'Plain Papadum',
    'King Prawn Balti',
    'Garlic Naan',
    'Mushroom Rice',
    'Paneer Tikka Masala',
    'Mango Chutney',
    'Plain Naan',
    'Tandoori Chicken (1/4)',
    'Vindaloo - Lamb',
    'Chapati',
    'Lamb Tikka',
    'Saag Paneer',
    'Aloo Chaat',
    'Chicken Pakora',
    'Chicken Chilli Garlic',
    'Lamb Biryani',
    'Keema Naan',
    'Red Sauce',
    'Korma - Prawn',
    'Peshwari Naan',
    'Pilau Rice',
    'Chicken Balti',
    'Special Fried Rice',
    'Chicken Tikka Masala',
    'Curry - Lamb',
    'Vegetable Rice',
    'Saag - Prawn',
    'Tandoori Chicken Masala',
    'Lamb Tikka Chilli Masala',
    'Saag Aloo',
    'Aloo Gobi',
    'Bhindi Bhajee',
    'Mint Sauce',
    'Chicken Biryani',
    'Madras - Chicken Tikka',
    'Bombay Aloo',
    'Onion Bhajee',
    'Sheek Kebab',
    'Onion Chutney',
    'Chicken Tikka (Main)',
    'Korma - Chicken',
    'Plain Rice',
    'French Fries',
    'Meat Samosa',
    'Keema Rice',
    'Lamb Hari Mirch',
    'Mushroom Bhajee',
    'Curry - Chicken',
    'Chicken Tikka Biryani',
    'Mixed Starter',
    'Bhuna - Chicken Tikka',
    'Madras - Lamb',
    'Masala Sauce',
    'Bottle Coke',
    'Tandoori Mixed Grill',
    'Korma Sauce',
    'Pathia - Prawn',
    'Chicken Tikka Jalfrezi',
    'Bhuna - Lamb',
    'Mixed Vegetable Curry',
    'Dupiaza - Lamb',
    'Lemon Rice',
    'Methi - Lamb',
    'Spicy Papadum',
    'Rogon - Lamb',
    'Chicken Tikka Karahi',
    'Bhuna - Chicken',
    'Lamb Mysore',
    'Dhansak - Chicken',
    'Madras - Chicken',
    'Chicken Tikka Chilli Masala',
    'Lal Mirch Chicken',
    'Korma - King Prawn',
    'Vindaloo - Chicken',
    'Vindaloo Sauce',
    'Chana Masala',
    'Dupiaza - Chicken',
    'Muttar Paneer',
    'Chicken Shashlick',
    'Vegetable Balti',
    'Cauliflower Bhajee',
    'Butter Chicken',
    'Prawn Balti',
    'Pathia - Chicken Tikka',
    'COBRA ( LARGE )',
    'House white wine 75cl',
    'Lime Pickle',
    'King Prawn Shaslick',
    'Stuffed Paratha',
    'Curry Sauce',
    'Raitha',
    'Bottle Diet Coke',
    'Tarka Dall',
    'Saag Dall',
    'Dhansak - Lamb',
    'Green Salad',
    'Vegetable Biryani',
    'Madras - King Prawn',
    'Rogon - Chicken',
    'Chicken Tikka',
    'Royal Paneer',
    'Lamb Sylhet',
    'Dupiaza - Chicken Tikka',
    'Saag - Chicken',
    'Saag Rice',
    'Lamb Tikka Masala',
    'Paneer Tikka Sizzler',
    'Chicken Mysore',
    'Lamb Chilli Garlic',
    'Tandoori Roti',
    'King Prawn Puree',
    'Dhansak Sauce',
    'Baingan Hari Mirch',
    'Puree',
    'Onion Naan',
    'Paratha',
    'Kulcha Naan',
    'Lemonade 1.5 ltr',
    'Diet Coke 1.5 ltr',
    'Coke 1.5 ltr',
    'Garlic Rice',
    'Onion Rice',
    'Perrier Water (750ml)',
    'Egg Rice',
    'Egg Paratha',
    'COBRA (330ML)',
    'Madras Sauce',
    'Bengal Salad',
    'Still Water (750ml)',
    'Prier Water (750ml)',
    'Onion Bhaji',
    'Chicken Chaat',
    'Prawn Puree',
    'Vegetable Roll',
    'Sheek Kehab',
    'Vegetable Samosa',
    'Aloo Methi',
    'Saag Bhajee',
    'Tandoori Fish',
    'Brinjal Bhajee',
    'Vegetable Mysore',
    'King Prawn Butterfly',
    'Dall Samba',
    'COBRA (660ML)',
    'Chicken Chaat Main',
    'Curry - Chicken Tikka',
    'Vindaloo - Chicken Tikka',
    'Madras',
    'Curry',
    'Vindaloo',
    'Tandoori Chicken (Main)',
    'Korma - Chicken Tikka',
    'Pathia - Lamb',
    'Chicken Karahi',
    'Dhansak - Chicken Tikka',
    'Chicken Tikka Pasanda',
    'Pathia - Chicken',
    'Lamb Tikka Jalfrezi',
    'Lamb Karahi',
    'Madras - Prawn',
    'Lamb Tikka (Main)',
    'Lamb Tikka Pasanda',
    'Lamb Tikka Garlic',
    'Chicken Tikka Garlic',
    'Mushroom - Chicken',
    'Sheek Kebab (Main)',
    'Saag - Chicken Tikka',
    'Curry - Prawn',
    'Saag - Lamb',
    'Korma - Lamb',
    'Mushroom - Lamb',
    'Rogon - Chicken Tikka',
    'Vindaloo - Prawn',
    'Methi - Chicken Tikka',
    'Vegetable Karahi',
    'Mushroom - Chicken Tikka',
    'Methi - Chicken',
    'Lamb Tikka Jeera',
    'Chicken Tikka Jeera',
    'Bhuna',
    'Saag',
    'Dhansak',
    'Pathia',
    'Korma',
    'Dupiaza',
    'Methi',
    'Rogon',
    'Mushroom',
    'Tandoori Chicken',
    'Chicken Roshni',
    'Lamb Balti',
    'Chicken Rezala',
    'Lamb Rezala',
    'Chicken Hari Mirch',
    'Lamb Shashlick',
    'Bhuna - Prawn',
    'Chicken Haryali',
    'Paneer Shaslick',
    'Paneer Tikka Karahi',
    'Lamb Achar',
    'Chicken Tikka Sizzler',
    'Lamb Tikka Karahi',
    'Prawn Karahi',
    'Lal Mirch Lamb',
    'Lamb Haryali',
    'Dhansak - Prawn',
    'Chicken Sylhet',
    'Lamb Tikka Sizzler',
    'Chicken Achar',
    'Dupiaza - Prawn',
    'Lamb Roshni',
    'Methi - Prawn',
    'Rogon - Prawn',
    'Mushroom - Prawn',
    'Lamb Tikka Biryani',
    'Chicken Tikka Balti',
    'Lamb Tikka Balti',
    'Prawn Biryani',
    'Paneer Tikka Balti',
    'Persian Lamb Biryani',
    'Persian Chicken Biryani',
    'Lamb Persian',
    'Curry - King Prawn',
    'Tandoori Fish (Main)',
    'Vindaloo - King Prawn',
    'Tandoori King Prawn Garlic',
    'Chicken Shashlick Curry',
    'King Prawn Hari Mirch',
    'Hazary Lamb Chilli Garlic',
    'Lamb Shashlick Curry',
    'Dhansak - King Prawn',
    'Bengal King Prawn',
    'Bhuna - King Prawn',
    'Hazary Lamb',
    'Bengal Fish Biryani',
    'Tandoori King Prawn Masala',
    'King Prawn Biryani',
    'Saag - King Prawn',
    'Dupiaza - King Prawn',
    'Pathia - King Prawn',
    'Bengal Fry Fish',
    'Bengal Fish Karahi',
    'Rogon - King Prawn',
    'Mushroom - King Prawn',
    'King Prawn Karahi',
    'Methi - King Prawn',
    'Kurma',
    'House Red wine 75cl'
  ];
}
